# Generated by Django 5.2 on 2025-04-27 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_picture', models.ImageField(blank=True, null=True, upload_to='product_pictures/')),
                ('product_name', models.CharField(default='', max_length=255)),
                ('product_price', models.IntegerField()),
                ('product_origin', models.CharField(default='', max_length=255)),
                ('product_description', models.CharField(default='', max_length=510)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(default='', max_length=255)),
                ('province', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('barangay', models.CharField(default='', max_length=255)),
                ('postal_code', models.CharField(default='', max_length=255)),
                ('home_address', models.CharField(default='', max_length=255)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
